fix(actions): Add test step, and disable linter

diff --git a/.github/actions/tests/action.yml b/.github/actions/tests/action.yml
--- a/.github/actions/tests/action.yml
+++ b/.github/actions/tests/action.yml
@@ -7,15 +7,10 @@ runs:
       shell: bash
       id: coverage
       run: |
-        # go test -coverprofile=coverage.out ./...
-        # coverage=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
-
-        # echo "Coverage is $coverage%"
- 
-        # if (( $(echo "$coverage > 90" | bc -l) )); then
-        #   echo "Coverage is greater than 90%"
-        #   exit 0
-        # else
-        #   echo "Coverage is not greater than 90%"
-        #   exit 1
-        # fi
+        echo "Running tests"
+        bash src/internal/tests/component/run_test.sh
+        if [ $? -ne 0 ]; then
+          echo "Tests failed"
+          exit 1
+        fi
+        echo "Tests passed"
